import math

CONFIG = {
    'train_data_path': '../../../../data/cleanTrain_accordion',
    'eval_data_path': '../../../../data/cleanTrain_bend',
    'train_result_path': 'results/',
    'train_record_path': 'train_record.txt',
    'eval_record_path': 'eval_record.txt',
    'model_path': 'current_model.pt',
    'rnn_hidden_size': 256,
    'rnn_num_layers': 1,
    'latent_code_num': 1,
    'learning_rate': 0.001,
    'z_rnn_loss_scalar': 2,
    'checkpoint_interval': 5000,
    'max_iter_num': 15001,
    'log_interval': 100,
    'eval_interval': 1000,
    'linear_schedule': 0.6,
    'rnn_type': 'RNN',
    'batch_size': 32,
    'kld_loss_scalar': 0.01,
    'eval_recons': False,
    'seq_len': 15,
    'base_len': 4,
    'ae': False,
    'is_save_img': True,
    'is_intrinsic_train': False,
    'is_normal_train': False,
    'is_stupid_train': True,
    'is_stupid_add_len': True,
}
